export const Question = [
    {
        prompt: "What is the rarest M&M color?",
        optionA: "Black",
        optionB: "Yellow",
        optionC: "Brown",
        optionD: "Red",
        answer: "C",
    },
    {
        prompt: "In what year were the first Air Jordan sneakers released?",
        optionA: "1984",
        optionB: "1983",
        optionC: "1985",
        optionD: "1982",
        answer: "A",
    },
    {
        prompt: "In a bingo game, which number is represented by the phrase “two little ducks”?",
        optionA: "11",
        optionB: "22",
        optionC: "18",
        optionD: "14",
        answer: "B",
    },
    {
        prompt: "According to Greek mythology, who was the first woman on earth?",
        optionA: "Hera",
        optionB: "Medusa",
        optionC: "Ariadne",
        optionD: "Pandora",
        answer: "D",
    },
    {
        prompt: "In which European city would you find Orly airport?",
        optionA: "Paris",
        optionB: "Milano",
        optionC: "London",
        optionD: "Amsterdam",
        answer: "A",
    },
    {
        prompt: "Which singer’s real name is Stefani Joanne Angelina Germanotta?",
        optionA: "Madonna",
        optionB: "Gwen Stephani",
        optionC: "Lady Gaga",
        optionD: "Cardi B",
        answer: "C",
    },
    {
        prompt: "Which country consumes the most chocolate per capita?",
        optionA: "Belgium",
        optionB: "Neatherland",
        optionC: "France",
        optionD: "Switzerland",
        answer: "D",
    },
    {
        prompt: "In the United Kingdom, what is the day after Christmas known as?",
        optionA: "Thanksgiving Day",
        optionB: "Holiday",
        optionC: "Boxing Day",
        optionD: "Saint Day",
        answer: "C",
    },
    {
        prompt: "What is the tallest breed of dog in the world?",
        optionA: "Akita",
        optionB: "The Great Dane",
        optionC: "Shiba Inu",
        optionD: "Dalmata",
        answer: "B",
    },
    {
        prompt: "How many ribs are in a human body?",
        optionA: "24",
        optionB: "22",
        optionC: "26",
        optionD: "28",
        answer: "A",
    },
    {
        prompt: "What is the world’s biggest island?",
        optionA: "Japan",
        optionB: "Mallorca",
        optionC: "Australia",
        optionD: "Greenland",
        answer: "D",
    },
    {
        prompt: "What color eyes do most humans have?",
        optionA: "Brown",
        optionB: "Blue",
        optionC: "Green",
        optionD: "Gray",
        answer: "A",
    },
    {
        prompt: "In which city was Anne Frank’s hiding place?",
        optionA: "Zurich",
        optionB: "Berlin",
        optionC: "Amsterdam",
        optionD: "Rome",
        answer: "C",
    },
    {
        prompt: "Which Disney film features the song ‘When You Wish Upon a Star’?",
        optionA: "Ariel",
        optionB: "Pinocchio",
        optionC: "Lion King",
        optionD: "The Beauty and the Beast",
        answer: "B",
    },
];